version: '3.3'

services:
  web-client:
    environment:
      - NODE_ENV=production
    image: vstay/web-client
    container_name: web-client
    restart: always
    expose:
      - 3000
# networks:
#   default:
#     external:
#       name: nginx-proxy
